SET REFERENTIAL_INTEGRITY FALSE;
ALTER TABLE ingredient ALTER COLUMN id RESTART WITH 1;
ALTER TABLE medicine ALTER COLUMN id RESTART WITH 1;
TRUNCATE TABLE ingredient RESTART IDENTITY;
TRUNCATE TABLE medicine RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
